storybookjs/presets

packages/preset-typescript/README.md
packages/preset-typescript/index.d.ts
packages/preset-typescript/index.js

Hi,
this fixes #16.
I've also fixed the outdated typings.
Thanks for the amazing work.
Matt'

[TS] Add optional manager transpilation.

---

packages/preset-typescript/README.md

I think so `tsLoaderOptions` is documented important than `tsDocgenLoaderOptions`.

add preset-typescript tsloader-option to README.md.

---

packages/preset-create-react-app/package.json

Hello, when testing https://github.com/storybookjs/presets/pull/25 I discovered that `helpers` directory is to been published. This PR fixes it.
Edit:
Tested locally

fix (build): Added helpers folder to files in preset-create-react-app

---

package.json

Now always fail test. Because of No tests found.
```
$ jest
No tests found
In /home/circleci/repo
26 files checked.
testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 0 matches
testPathIgnorePatterns: /node_modules/ - 26 matches
Pattern:  - 0 matches
error Command failed with exit code 1.
```
Added [passWithNoTests flag](https://jestjs.io/docs/en/cli#passwithnotests) at jest.

Add passWithNoTests flag at jest

---

packages/preset-create-react-app/.storybook/presets.js
packages/preset-create-react-app/README.md
packages/preset-create-react-app/helpers/getModulePath.js
packages/preset-create-react-app/index.js
packages/preset-create-react-app/package.json

This PR removes the need to set `useTsDocgenLoader`, and updates path resolution for TS projects.

feat/fix: remove tsdocgen option and resolve ts paths

---

packages/preset-create-react-app/helpers/getReactScriptsPath.js

Hello,
I fixed the bug that was breaking Windows react-scripts resolution. It was just an erroneous regex that was capturing the entire path when it needed to clip the "\bin\react-scripts.js."
Thanks for the useful package!
Matt
Closes #48

Fixed bug in Windows scripts dir resolution regex (closes #48)

---

packages/preset-typescript/index.js

When just using `module.exports = ['@storybook/preset-typescript'];` in `presets.js` the generated webpack config for `.tsx?$` contains undefined values:
```
{
test: /\.tsx?$/,
use: [
{
loader: '.../node_modules/ts-loader/index.js',
options: undefined
},
{
loader: '.../node_modules/react-docgen-typescript-loader/dist/index.js',
options: undefined
}
],
include: undefined
},
```
This causes an error with `ts-loader-6.2.1`
```
ERROR in ./.storybook/config.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for .../.storybook/config.ts.
...
```
Error is caused by `include: undefined`. To solve this I propose to init all (tsLoaderOptions, tsDocgenLoaderOptions, include) options to avoid undefined vales in webpack config ts-loader section and …

preset-typescript: init tsLoaderOptions, tsDocgenLoaderOptions, include options

---

packages/preset-typescript/.storybook/presets.ts
packages/preset-typescript/README.md
packages/preset-typescript/index.js
packages/preset-typescript/package.json
packages/preset-typescript/tsconfig.json
yarn.lock

Use [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin) in preset typescript to make builds faster and update preset typescript documentation to cover all available options
https://github.com/storybookjs/presets/issues/54

Preset-typescript: Use fork-ts-checker-webpack-plugin

---

examples/README.md
examples/cra-sb-beta/.storybook/main.js
packages/preset-create-react-app/README.md
packages/preset-create-react-app/package.json
packages/preset-create-react-app/src/helpers/processCraConfig.ts
packages/preset-create-react-app/src/options.ts
packages/preset-create-react-app/tsconfig.json
packages/preset-typescript/.storybook/presets.ts
packages/preset-typescript/README.md
yarn.lock

This is the other side of PR https://github.com/storybookjs/storybook/pull/9157.
This allows the CRA preset to load without loaders inserted downstream - unless a user explitely inserts additional loaders.

Add support for CRA without overrides

---

packages/preset-ant-design/README.md

Antd needs less-loader, but  `preset-create-react-app` prevents  `preset-ant-design` to override webpack config. 
This tip may save developers time.

docs(antd): tips for override file loader

---

packages/preset-create-react-app/src/helpers/processCraConfig.ts

When using pnpm, sometimes dependencies are stored in folders that include associations with other dependencies.  The loader path test will, in some cases, return a false positive, unless it is bounded with the path separator.
For example, if `url-loader` loader path is:
```sh
${workspaceRoot}/node_modules/.pnpm/registry.npmjs.org/url-loader/2.3.0_file-loader@4.3.0+webpack@4.41.2/node_modules/url-loader/dist/cjs.js
```
Then line 66 in `processCraConfig` will return a false positive, and the spread operator at line 79 will throw.
https://github.com/storybookjs/presets/blob/4fa600318b1c17edc7bd11d5eaeb1d3f5969ed2a/packages/preset-create-react-app/src/helpers/processCraConfig.ts#L58-L83
It would be possible to just include `path.sep` in the `includes()` functions, like this
```ts …
```

[preset-create-react-app] fix loader path tests

---

packages/preset-typescript/README.md

When I went to install `preset-typescript` last time, I was confused how to use it with the new `main.js` configuration. Turns out its almost exactly the same (of course).
Updated the Typescript preset's readme so that it's similar style to the CRAs preset's readme.

Update preset-typescript readme to be similar to cra-preset readme

---

packages/preset-typescript/index.js

Since #73 the `include` option for the typescript loader defaults to an empty array, which essentially makes it required (`[]` never matches). This PR only adds `include` to the loader if something was provided in the addons config.
Alternative approach: clarify in readme that `include` is not an advanced option but required.

fix(preset-typescript): don't default to empty include option

---

packages/preset-typescript/index.js
packages/preset-typescript/package.json

This adds `appendTsSuffixTo` if the framework is Vue and rolls up two related PRs that help minimize additional manual configuration.
- ~Remove `react-typescript-docgen-loader` from `preset-typescript` (rollup #68)~ merged
- ~Don't default to empty include option (rollup #106)~ merged
- Add appendTsSuffixTo to tsLoader options if framework is vue
**Example repo**
https://github.com/graup/storybook-vue-typescript
This actually doesn't require any custom config now, as you can see [here](https://github.com/graup/storybook-vue-typescript/blob/master/.storybook/main.js) 🎉
Just add the preset (and apply my storybook patch, which I'll introduce back to storybook later)

Improve compatibility of preset-typescript with Vue

---

packages/preset-create-react-app/src/index.ts

There is a bug in `@storybook/preset-create-react-app` which prevents the use of custom `react-scripts` packages with the `scriptsPackageName` option.
This pull request addresses the following issues:
1. Node's `require.resolve()` returns a **filename**, not the pathname of the resolved module. E.g. `require('my-custom-react-scripts') => '/path/to/node_modules/my-custom-react-scripts/index.js'`. This causes `@storybook/preset-create-react-app` to incorrectly build the path for the Webpack configuration file as `/path/to/node_modules/my-custom-react-scripts/index.js/config/webpack.config.js`.
2. `react-scripts` by default do not define a `main` entry file in `package.json`, which causes `require.resolve()` to **fail** with `MODULE_NOT_FOUND` unless the `react-scripts` fork is modified to …

fix: resolve react-scripts path from scriptsPackageName

---

packages/preset-typescript/src/helpers/processConfig.ts

Fix case where the babel include rule is nullish, and array spread fails.
Self-merging @mrmckeb

Preset-typescript: Fix for nullish babel include

---

packages/preset-create-react-app/src/index.ts

This sets the `PUBLIC_URL` to `.`, which allows serving the same build from different paths ([see CRA docs](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths)).
Resolves: https://github.com/storybookjs/storybook/issues/4645.

fix(cra): set PUBLIC_URL for static builds

---

packages/preset-scss/README.md

The readme for `preset-scss` does not have documentation for declaring the options for addons/preset on main.js. This is needed as using preset.js and main.js is not supported right now.

[preset-scss] Update README.md for addon declaration on main.js

---

packages/preset-create-react-app/package.json

Why ?
Because when launching e2e with verdaccio, this preset is installed in an environment where @storybook/node-logger@5.3.17 doesn't exists

Use * on node-logger dependency version

---

examples/cra-ts/.env
examples/cra/.env
package.json
packages/preset-create-react-app/src/index.ts
yarn.lock

As suggested by @ndelangen, this should resolve https://github.com/storybookjs/storybook/issues/11045.
Our new TypeScript defaults were conflicting with this preset, so all default Storybook Babel config is ignored - however user config (`main` files, or `babelrc` files) is still accepted.

fix(cra): ignore default Babel config from Storybook

---

packages/preset-create-react-app/README.md

Importing `path` looks irrelevant and coudl be misleading.

Remove irrelevant import from Advanced usage

---

.github/workflows/ci.yml
.prettierignore
examples/cra-ts/package.json
examples/cra-ts/src/serviceWorker.ts
examples/cra/package.json
examples/cra/src/serviceWorker.js
examples/ts-react/package.json
examples/ts-vue/package.json
package.json
packages/preset-create-react-app/package.json
packages/preset-create-react-app/src/helpers/checkPresets.ts
packages/preset-create-react-app/src/helpers/mergePlugins.ts
packages/preset-create-react-app/src/helpers/processCraConfig.ts
packages/preset-create-react-app/src/index.ts
packages/preset-create-react-app/src/types.ts
packages/preset-typescript/src/helpers/processConfig.ts
yarn.lock

This updates the CRA preset to mirror the config as of #11106.

feat(cra): move to react-docgen-typescript-plugin

---

packages/preset-scss/index.js

**What's the problem this PR addresses?**
`@storybook/preset-scss` is passing webpack loaders as strings instead of their absolute location causing it to rely on hoisting to place them next to `@storybook/core` which is not guaranteed
**How did you fix it?**
Use `require.resolve` to get the absolute path of the loaders

fix(preset-scss): require.resolve webpack loaders

---

README.md

While it might now be 100% correct it is the closest I could find to a preset gallery. The current link 404s

Update preset gallery link

---

packages/preset-ie11/README.md
packages/preset-ie11/package.json
packages/preset-ie11/src/index.ts
packages/preset-ie11/tsconfig.json
yarn.lock

IE 11 keeps being a pain for storybook users and anyone brave enough to use it.
While more and more tools are shutting down it's support. Including Microsoft. Storybooks should be prepared as well with opt-in support.
The idea is to let user 
- opt in additional transpilers for external modules
- force preset env to be use ie 11
This would improve performances when not used for storybook out of the box.
The original need of this preset is due to the way preset-create-react-app works. It's overriding Storybook default's babel config and removing es6 transpilers (for libs like acorn, semver, that drops IE 11)

feat: add IE 11 preset

---

packages/preset-create-react-app/package.json
packages/preset-create-react-app/src/helpers/getReactScriptsPath.ts
packages/preset-create-react-app/src/index.ts

**What's the problem this PR addresses?**
- `@storybook/preset-create-react-app` is using the `pnpapi` directly to query the **top level** workspace to try to locate `react-scripts` but this doesn't work when in a monorepo where the top level probably doesn't depend on `react-scripts` and even if it did, it might not be the same version as the one the workspace depends on
- `react-scripts` doesn't have a `main` field nor a `index` file so resolving it fails
Fixes https://github.com/storybookjs/presets/issues/58
Fixes https://github.com/storybookjs/presets/issues/161
Fixes https://github.com/storybookjs/presets/issues/168
Fixes https://github.com/storybookjs/storybook/issues/10078
Closes https://github.com/storybookjs/presets/pull/166
**How did you fix it?**
- Remove the PnP specific logic …

preset-create-react-app: Support monorepos and PnP

---

package.json
packages/preset-create-react-app/package.json
packages/preset-create-react-app/src/helpers/mergePlugins.ts
packages/preset-create-react-app/src/helpers/processCraConfig.ts
packages/preset-create-react-app/src/index.ts
packages/preset-create-react-app/src/types.ts
packages/preset-create-react-app/tsconfig.json
packages/preset-ie11/package.json
yarn.lock

This PR makes the required updates to allow the preset to work with CRAv5.
Due to an issue with CRAv5 alpha (fixed in the next release), the latest version of `postcss-normalize` should be manually installed.

CRA: Add compatibility for CRA v5

---

packages/preset-create-react-app/package.json
packages/preset-create-react-app/src/index.ts
yarn.lock

As requested in the previous PR, the types are removed for the sake of not adding an extra dependency

fix: remove core-common types and peerDep

---

packages/preset-create-react-app/src/index.ts
packages/preset-create-react-app/src/types.ts

To add support for:
```js
core: {
builder: {
name: 'webpack5',
options: {
fsCache: true,
lazyCompilation: true,
},
},
},
```
See inline comment for approach (as discussed with @shilman)

Add support for `builder.core` options to CRA preset

---

packages/preset-scss/README.md

the yarn script installs the latest versions of those libraries which are no longer compatible with webpack 4 which is what storybook runs on.
Addresses issue #195

update install instructions

---

packages/preset-ant-design/index.js

After less-loader's version upgrade, such error shown during attempt to start storybook
```
ERROR in ./node_modules/antd/lib/dropdown/style/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ref--7-2!./node_modules/less-loader/dist/cjs.js??ref--12-0!./node_modules/antd/lib/dropdown/style/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
- options has an unknown property 'modifyVars'. These properties are valid:
object { lessOptions?, additionalData?, sourceMap?, webpackImporter? }
```
It requires to set lessOptions inside less-options object:
Before:
```
presets: [
{
name: …
```

Fixed 'Invalid options object' error
